name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }

    steps:
      - uses: actions/checkout@v3

      - name: Build the poster
        run: pdflatex poster.tex
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Poster
          path: |
            *.pdf